<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArrisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrisRepository extends EntityRepository
{
    /**
    *Get arrises
    * @return array of object Arris or false if fail
    **/
    public function getArrises()
    {
        $arrises = $this->findAll();
        if(!$arrises) return false;
        return $arrises;
    }//end func
    
    
    public function getAll()
    {
        $all = $this->findAll();
        if(!$all) return false;
        return $all;
    }//end func
    
    /**
    *Get arris
    * @param int $id Id of material
    * @return object Arris or false if fail
    **/
    public function getArris($id)
    {
        $arris = $this->find($id);
        if($arris) return $arris;
        return false;
    }//end func
    
}
