<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
   /**
    *Get article with given slug and have status SHOW
    * @param string $slug
    * @return object Article
    **/
   public function getArticle($slug)
    {
        $article = $this->findOneBy(array('slug'=>$slug,'type'=>'SHOW'));
        if($article) return $article;
        return false;
    }//end func
    
     /**
    *Get all articles
    * @return array of objects Article
    **/
   public function getAll()
    {
        $all = $this->findAll();
        if(!$all) return false;
        return $all;
    }//end func
}
