<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function getAll()
    {
        $all = $this->findAll();
        if ( !$all ) return false;
        return $all;
    }//end func
    
    public function getBrandsByMaterial($material)
    {
        if (!is_object($material)) return false;
        $all = $this->findAll();
        if ( !$all ) return false;
        $materialBrands = $material->getBrand();
        $brands = array();
        foreach ( $all as $item )
        {
            if ( in_array($item->getBrand(),$materialBrands) ) $brands[] = $item;
        }
        return (count($brands))? $brands : false;
    }//end func
    
    public function getBrand($slug)
    {
        $brand = $this->findOneBy(array('brand'=>$slug));
        if ($brand) return $brand;
        return false;
    }//end func
    
}
