<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
     /**
    *Get All
    * @return array of object Gallery or false if fail
    **/
    public function getAll()
    {
        $all = $this->findAll();
        if(!$all) return false;
        return $all;
    }//end func
    
}
