<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * get list image file for insert into MCETiny editor
     * @return array $files Associative array of files or empty array if fail
     **/
    public function getListImage()
    {
        $images = $this->findAll();
        if(!$images) return array();
        $files = array();
        foreach( $images as $image )
        {
            $files[$image->getTitle()] = $image->getRelativeLinkToImg();
        }
        return $files;
        
    }//end func
    
    public function getAll()
    {
        $all = $this->findAll();
        if(!$all) return false;
        return $all;
    }//end func
    
    public function getGallery($gal)
    {
        if (!$gal) return false;
        $all = $this->findAll();
        if (!$all) return false;
        $images = array();
        foreach( $all as $image )
        {
            $gallerys = $image->getGallery();
            if (!is_array($gallerys)) return false;
            if ( in_array($gal,$gallerys) ) $images[] = $image;
        }
        return ($images)? $images : false;
    }//end func
    
    public function getImageNames($names)
    {
        if (is_array($names))
        {
            $images = array();
            foreach ( $names as $name )
            {
                $images[] = $this->findOneBy(array('title'=>$name));
            }
            return $images;
        }
        elseif ( is_string( $names ) )
        {
            return $this->findOneBy(array('title'=>$names));
        }
        else return false;
    }//end func
    
}
