<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function saveOrder($name, $email, $phone, $skype, $material, $product, $description )
    {
        $order = new Order();
        $em = $this->getEntityManager();
        $order->setName($name);
        $order->setEmail($email);
        $order->setPhone($phone);
        $order->setSkype($skype);
        $order->setMaterial($material);
        $order->setProduct($product);
        $order->setDescription($description);
        $order->uploadImage();
        $em->persist($order);
        $em->flush();
    }//end func
    
}
