<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
    *Get page with given slug and have status SHOW
    * @param string $slug
    * @return object Page
    **/
    public function getPage($slug)
    {
        $page = $this->findOneBy(array('slug'=>$slug,'type'=>'SHOW'));
        if($page) return $page;
        return false;
    }//end func
    
    
}
