<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{
    public function getPartners()
    {
        $partners = $this->findBy(array('logoshow'=>true));
        if(!$partners) return false;
        return $partners;
    }//end func
    
     public function getAll()
    {
        $partners = $this->findBy(array('logoshow'=>true));
        if(!$partners) return false;
        return $partners;
    }//end func
    
     public function getPartner($id)
    {
        $partner = $this->find($id);
        if($partner) return $partner;
        return false;
    }//end func
    
    
}
