<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
    *Get All
    * @return array of object Product or false if fail
    **/
    public function getAll()
    {
        $all = $this->findAll();
        if(!$all) return false;
        return $all;
    }//end func
    
    /**
    *Get One
    * @return object Product or false if fail
    **/
    public function getOne($id)
    {
        $one = $this->find($id);
        if($one) return $one;
        return false;
    }//end func
    
}
