<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getProjects()
    {
        $projects = $this->findAll();
        if(!$projects) return false;
        return $projects;
    }//end func
    
    public function getProject($id)
    {
        $project = $this->find($id);
        if($project) return $project;
        return false;
    }//end func
    
}
