<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    public function getAll()
    {
        $settings = $this->findAll();
        if(!$settings) return false;
        $result = array();
        foreach( $settings as $setting )
        {
            $result[$setting->getName()] = $setting->getValue();
        }
        return $result;
    }//end func
    
    public function getSettings()
    {
        $settings = $this->findAll();
        if(!$settings) return false;
        $result = array();
        foreach( $settings as $setting )
        {
            $result[$setting->getName()] = $setting->getValue();
        }
        return $result;
    }//end func
    
     public function getValue($name)
    {
        $set = $this->findOneBy(array('name'=>$name));
        if($set) return $set->getValue();
        return false;
    }//end func
    
}
