<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository
{
    public function getSlides()
    {
        $slides = $this->findAll();
        if(!$slides) return false;
        return $slides;
    }//end func
    
    public function getAll()
    {
        $slides = $this->findAll();
        if(!$slides) return false;
        return $slides;
    }//end func
    
    public function getSlidesByCategory($cat)
    {
        $slides = $this->findBy(array('category'=>$cat));
        if(!$slides) return false;
        return $slides;
    }//end func
    
}
