<?php

namespace Alians\StoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SonetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SonetRepository extends EntityRepository
{
    public function getAll()
    {
        $items = $this->findAll();
        if(!$items) return false;
        return $items;
    }//end func
}
