Alians\StoneBundle\Entity\Article:
    type: entity
    table: article
    repositoryClass: Alians\StoneBundle\Entity\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
            nullable: false
        content:
            type: text
            nullable: true
        htmlTitle:
            column: html_title
            type: string
            length: '255'
            nullable: true
        metaKeywords:
            column: meta_keywords
            type: string
            length: '255'
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: '255'
            nullable: true
        type:
            type: string
            length: '255'
            nullable: true
        slug:
            type: string
            length: '255'
        img:
            type: string
            length: '255'
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
           
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, uploadImage, checkSlug  ]
        preUpdate: [ setUpdatedAtValue, uploadImage, checkSlug  ]