Alians\StoneBundle\Entity\Gallery:
    type: entity
    table: gallery
    repositoryClass: Alians\StoneBundle\Entity\GalleryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            nullable: true
        slug:
            type: string
            length: '255'
            nullable: true
        description:
            type: text
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, checkSlug ]
        preUpdate: [ setUpdatedAtValue, checkSlug ]