Alians\StoneBundle\Entity\Image:
    type: entity
    table: image
    repositoryClass: Alians\StoneBundle\Entity\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
            nullable: true
        description:
            type: string
            length: '255'
            nullable: true
        gallery:
            type: string
            length: '255'
            nullable: true
        img:
            type: string
            length: '255'
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, uploadImage ]
        preUpdate: [ setUpdatedAtValue, uploadImage ]