Alians\StoneBundle\Entity\Material:
    type: entity
    table: material
    repositoryClass: Alians\StoneBundle\Entity\MaterialRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
            nullable: true
        content:
            type: text
            nullable: true
        brand:
            type: string
            length: '255'
            nullable: true
        slug:
            type: string
            length: '255'
            nullable: true
        category:
            type: string
            length: '255'
            nullable: false
            default: '.'
        showmenu:
            type: boolean
            nullable: true
        gallery1:
            type: string
            length: '255'
            nullable: true
        gallery2:
            type: string
            length: '255'
            nullable: true
        gallery3:
            type: string
            length: '255'
            nullable: true
        text1:
            type: text
            nullable: true
        text2:
            type: text
            nullable: true
        text3:
            type: text
            nullable: true
        img:
            type: string
            length: '255'
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, uploadImage, checkSlug ]
        preUpdate: [ setUpdatedAtValue, uploadImage, checkSlug ]