Alians\StoneBundle\Entity\Partner:
    type: entity
    table: partner
    repositoryClass: Alians\StoneBundle\Entity\PartnerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            nullable: true
        logoshow:
            type: boolean
            nullable: true 
        img:
            type: string
            length: '255'
            nullable: true
        description:
            type: text
            nullable: true
        logo_url:
            type: string
            length: '255'
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, uploadImage ]
        preUpdate: [ setUpdatedAtValue, uploadImage ]