Alians\StoneBundle\Entity\Slide:
    type: entity
    table: slide
    repositoryClass: Alians\StoneBundle\Entity\SlideRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
            nullable: true
        content:
            type: text
            nullable: true
        category:
            type: integer
            nullable: true
        img:
            type: string
            length: '255'
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, uploadImage ]
        preUpdate: [ setUpdatedAtValue, uploadImage ]